### ISSUE TITLE
set up flags for forum posts and comments

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/forum.backdropcms.org#2]
posts:
* Frequently Asked Question (moderator)

comments:
* Spam / Abusive (everyone)
* Helpful (everyone)
* Accepted answer (node author)

**Comment by klonos** [comment]
For spam/abusive and helpful, I think that these should be votes instead of flags. I've seen cases where the abuser marks other people's comments as spam/abusive, so if that was a vote thing, we could have a threshold after which the comment (or an entire post) gets unpublished and the forum moderator is called for final action (deletion of content and/or user). This will crowd-source some of the moderators' job.

In general we'll need the Voting API and certain voting modules ported if we want features like user badges implemented (+1 voting on user profiles).

**Comment by jenlampton** [comment]
> I think that these should be votes instead of flags.

We can count flags exactly the same way as votes. There's no difference in function, only in technical implementation.

**Comment by klonos** [comment]
> > I think that these should be votes instead of flags.
> 
> We can count flags exactly the same way as votes.

Was not aware of that. I always thought that flags is an on/off thing (and users with proper permissions could toggle them) while votes are a count (and users with proper permissions could increment/decrement them). Huh.

**Comment by jenlampton** [comment]
That's a correct assessment, but if we need a count, we can count the flags. And a user can toggle on/off their vote too, right? :)

**Comment by tomgrandy** [comment]
Vote, not flag.  If the end result is the same, then having the name changed is sufficient.

**Comment by jenlampton** [comment]
This is done :)
