### ISSUE TITLE
Elaborating on forum features (external link to CMX.arbolis.net)

### ISSUE THREAD

**Issue by FuzboleroXV** [backdrop-ops/forum.backdropcms.org#20]
Here is my (updated today) take on the forum features that the CMX community distro will be looking at, which we hope can be based on Backdrop (draft post under development, yet still public):

https://cmx.arbolis.net/content/articles/qommunity-features-strategy-comments-everywhere%2C-so-'forum'-is-not-the-same-anymore

**Comment by klonos** [comment]
Hello @FuzboleroXV. Having read the article on arbolis.net and also listened to your thoughts expressed during the meetings, I have to say that either Drupal 7 or Backdrop does seem like a good platform for you to build your specific distribution.

You seem to have very specific needs and features outlined that can either be accomplished by core or contrib modules. I would personally not go with D8, as a lot of modules that you might need along the way have not been ported yet (D7 on the other hand has been around for quite a while now). Having said that, I need to also note that quite a lot of modules have not yet been ported to Backdrop either. So, you'll need to either be prepared to work on the porting yourselves as a community, or hire a person (or a group of people) to work on that.

As for which core version to choose (or which CMS for that matter), that's entirely up to you. You'll need to carefully examine the choices, define features that you require and make a decision. Be prepared for the fact that no choice will be a perfect fit out of the box, but if I were you, I'd make a choice and go with it soon. I have heard you mention that you've been looking for a platform since D6! ...now, that's a long wait and if you sit there just talking about it and waiting for a CMS that does *every single thing* that you are planning to offer as a feature, then I'm afraid your quest will be an endless one. You see as CMSes evolve, so does the society and its needs, and that will inevitably make your list of features grow and perpetuate the wait. It'll be a vicious circle.

Now, when it comes to Backdrop, I can tell you that nobody will guarantee that core will include all the features you are planning or that contrib will be enough with whatever will be ported from D7. If we see value in them "for the 80%", then yes, things might eventually be moved to core either as is, or partially. I would suggest to start giving it a go, then help by porting missing modules from d.org. If there is a feature or functionality that neither core nor any existing contrib module offers, then create a new, custom one yourselves (and please consider making it publicly available). Take a look at what the [Open Atrium](https://www.drupal.org/project/openatrium) distribution is doing in d.org: they use core + [Organic Groups](https://www.drupal.org/project/og) + [Panopoly](https://www.drupal.org/project/panopoly). The last one, is not actually a contrib module, but rather a "base distribution" (in the same sense that there exist base themes that you can base your own theme off of). In their project page, you'll see that they are using core + existing d.org contrib modules + their own, custom ones. A module/theme "ecosystem" of "Panopoly xyz" projects.

> To make everything happen, Panopoly bundles a currated set of contributed modules and third party libraries with its own custom modules including Panopoly Admin, Panopoly Core, Panopoly Images, Panopoly Magic, Panopoly Pages, Panopoly Search, Panopoly Theme, Panopoly Users, Panopoly Widgets, and Panopoly WYSIWYG.

I think from what I've gathered about your project so far, that this would be the best way for yo to go to.

..just my 2c.
