### ISSUE TITLE
Add a Frequently Asked Questions page 

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/forum.backdropcms.org#8]
There should be a list of FAQs selected by moderators, and easily accessible for anyone new to the site. New visitors could browse this list first, before needing to dig in deeper.

Tech specs: This is a moderator-only flag for "FAQ" and a view.

**Comment by stpaultim** [comment]
I like the FAQ and think it's working fine, however as someone still relatively new to using forums.backdropcms.org I found myself questioning exactly what the FAQ was - meaning, how it is generated?

I think that because I could see the comment count on the page and the author of the question - I found myself wondering, how did this become a FAQ based upon one person asking it? I began to wonder how the items were selected, assuming that either the comment count or the author had something to do with it. 

In the end, these questions did not prevent my usage of the page or even make it more difficult. These questions just distracted me for a short time, before I went on with my search. 

Personally on the FAQ, I would do the following:

1. Add a short note "FAQ questions are curated by the moderator."
2. On the main view, hide the author and comment count. On that particular page, the information is unnecessary and was distracting to me. On a FAQ page, the only really relevant information is the question being asked. 

Again, sharing this feedback with the clear understanding that this is very low priority.

**Comment by BWPanda** [comment]
Here's a PR that addresses @stpaultim's suggestions: https://github.com/backdrop-ops/forum.backdropcms.org/pull/120

![image](https://user-images.githubusercontent.com/2385329/103853953-68353000-5103-11eb-93c4-f377b5737425.png)

The header wording can probably use some feedback/changes...

**Comment by stpaultim** [comment]
@BWPanda - Thanks for doing this. I like the change and consider it an improvement. 

Your suggested text is fine. Here is an alternatives suggestion that is a bit shorter. 

Current PR:
`These FAQs (Frequently Asked Questions) are questions that users have asked in the forum. Moderators have decided that these questions (and their answers) will likely benefit lots of users, and have added them here for easier access.`

Alternative:
`These FAQs (Frequently Asked Questions) are questions that users have asked in the forum and have been selected by moderators for inclusion on this page.`

This is just shorter and more direct. But, your text is also good. I'm fine with either.

**Comment by BWPanda** [comment]
Ooh, I like yours!

**Comment by BWPanda** [comment]
PR updated with the following header text (slightly re-worded from @stpaultim's suggestion, just to get rid of the "these questions are questions..." duplication):

> These FAQs (Frequently Asked Questions) have been asked by users in the forum, and have been selected by moderators for inclusion on this page.
