### ISSUE TITLE
Provide a list of all my own posts

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/forum.backdropcms.org#9]
As a forum contributor, It would be nice if all the topics I either authored, or I have commented on were easy to find in a single place.

tech specs: this is a view (or maybe two views) of all nodes I have authored, and all nodes I have commented on.

**Comment by docwilmot** [comment]
I'm not certain this will be useful anymore, because we now have a list of posts I'm following, which will include every post youve made, or commented in, or been mentioned in. Plus, youll be able to stop receiving emails from any of your followed posts but still keep them as posts youre following, so there really will be little need to ever stop following any posts. Do you really need to list everywhere youve ever posted, or just the important ones youre following? I dunno.

**Comment by jenlampton** [comment]
> so there really will be little need to ever stop following any posts

Even though there may be little need, I would guess that people's actual behavior will be to stop following issues, rather than opt-out of emails. Let's leave this issue open (but feel free not to implement) until we have an idea of what people are doing on the site.

**Comment by jenlampton** [comment]
It looks like this exists already, on the `My profile` page. Closing.
