### ISSUE TITLE
Flag/highlight new posts in the forum

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/forum.backdropcms.org#91]
We got this feature request for the forum in Gitter today:

> I really need new-message indicators on the forum, and don't know if they don't exist or they're not turned on.

**Comment by jenlampton** [comment]
I've added the `new` marker to the taxonomy/term view:
https://forum.backdropcms.org/forum/how-and-troubleshooting

<img width="1195" alt="Screen Shot 2019-11-17 at 5 49 28 PM" src="https://user-images.githubusercontent.com/397895/69018769-a3562c00-0962-11ea-90d9-8d74cc635ad8.png">

I'm going to close this ticket, but please re-open if it turns out we need them anywhere else!
